const express = require('express');
const router = express.Router();
const axios = require('axios');

const CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET;

function authHeader() {
  return `Basic ${Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64')}`;
}

async function ensureFreshToken(req) {
  if (!req.session.spotifyTokens) return false;

  const { access_token, refresh_token, expires_at } = req.session.spotifyTokens;

  if (Date.now() < expires_at - 2 * 60 * 1000) {
    return access_token;
  }

  try {
    const res = await axios.post(
      'https://accounts.spotify.com/api/token',
      new URLSearchParams({ grant_type: 'refresh_token', refresh_token }),
      {
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          Authorization: authHeader(),
        },
      },
    );

    req.session.spotifyTokens = {
      access_token: res.data.access_token,
      refresh_token: res.data.refresh_token || refresh_token,
      expires_at: Date.now() + res.data.expires_in * 1000,
    };

    return res.data.access_token;
  } catch (err) {
    console.error('Token refresh failed:', err.response?.data || err.message);
    return false;
  }
}

// POST /api/spotify/search — search Spotify for a list of songs
router.post('/search', async (req, res) => {
  const token = await ensureFreshToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated with Spotify.' });

  const { songs } = req.body;
  if (!Array.isArray(songs)) return res.status(400).json({ error: 'songs array required.' });

  const results = await Promise.all(
    songs.map(async (song) => {
      try {
        const query = `track:${encodeURIComponent(song.title)} artist:${encodeURIComponent(song.artist)}`;
        const searchRes = await axios.get('https://api.spotify.com/v1/search', {
          params: { q: query, type: 'track', limit: 1 },
          headers: { Authorization: `Bearer ${token}` },
        });

        const track = searchRes.data.tracks?.items?.[0];
        if (!track) {
          const fallbackRes = await axios.get('https://api.spotify.com/v1/search', {
            params: { q: encodeURIComponent(song.title), type: 'track', limit: 1 },
            headers: { Authorization: `Bearer ${token}` },
          });
          const fallback = fallbackRes.data.tracks?.items?.[0];
          if (fallback) {
            return {
              ...song,
              found: true,
              track_uri: fallback.uri,
              track_id: fallback.id,
              spotify_title: fallback.name,
              spotify_artist: fallback.artists.map((a) => a.name).join(', '),
              album: fallback.album.name,
              album_art: fallback.album.images?.[1]?.url || fallback.album.images?.[0]?.url || null,
              preview_url: fallback.preview_url,
              external_url: fallback.external_urls.spotify,
            };
          }
          return { ...song, found: false };
        }

        return {
          ...song,
          found: true,
          track_uri: track.uri,
          track_id: track.id,
          spotify_title: track.name,
          spotify_artist: track.artists.map((a) => a.name).join(', '),
          album: track.album.name,
          album_art: track.album.images?.[1]?.url || track.album.images?.[0]?.url || null,
          preview_url: track.preview_url,
          external_url: track.external_urls.spotify,
        };
      } catch {
        return { ...song, found: false };
      }
    }),
  );

  res.json({ results });
});

// POST /api/spotify/create-playlist
router.post('/create-playlist', async (req, res) => {
  const token = await ensureFreshToken(req);
  if (!token) return res.status(401).json({ error: 'Not authenticated with Spotify.' });

  const userId = req.session.spotifyUser?.id;
  if (!userId) return res.status(401).json({ error: 'User session not found.' });

  const { bookTitle, bookAuthor, songs } = req.body;
  const trackUris = songs.filter((s) => s.track_uri).map((s) => s.track_uri);

  if (!trackUris.length) {
    return res.status(400).json({ error: 'No Spotify tracks to add.' });
  }

  try {
    const playlistRes = await axios.post(
      `https://api.spotify.com/v1/me/playlists`,
      {
        name: `${bookTitle} — Book Playlist`,
        description: `AI-curated playlist for "${bookTitle}" by ${bookAuthor}. Generated by BookPlaylist.app`,
        public: true,
      },
      { headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' } },
    );

    const playlistId = playlistRes.data.id;
    const playlistUrl = playlistRes.data.external_urls.spotify;

    for (let i = 0; i < trackUris.length; i += 100) {
      const batch = trackUris.slice(i, i + 100);
      const addRes = await fetch(
        `https://api.spotify.com/v1/playlists/${playlistId}/items`,
        {
          method: 'POST',
          headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ uris: batch }),
        },
      );
      if (!addRes.ok) {
        const addData = await addRes.json();
        throw new Error(`Add tracks failed: ${addRes.status} ${JSON.stringify(addData)}`);
      }
    }

    res.json({ success: true, playlistUrl, trackCount: trackUris.length });
  } catch (err) {
    console.error('Create playlist error:', err.response?.data || err.message);
    res.status(500).json({ error: 'Failed to create Spotify playlist.' });
  }
});

module.exports = router;
